version: '3.3'
services:

  signup-homepage:
    image: <your-dtr-domain>/dockersamples/mta-dev-signup-homepage:v1
    deploy:
      endpoint_mode: dnsrr
      placement:
        constraints:
        - node.platform.os == windows
      replicas: 2
    networks:
      - app-net

  signup-app:
    image: dockersamples/mta-dev-signup-app:v4
    ports:
    - mode: host
      published: 80
      target: 80
    deploy:
      endpoint_mode: dnsrr
      placement:
        constraints:
        - node.platform.os == windows
    networks:
      - app-net

  signup-db:
    image: dockersamples/mta-dev-signup-db:v1
    deploy:
      endpoint_mode: dnsrr
      placement:
        constraints:
        - node.platform.os == windows
    networks:
      - app-net

  message-queue:
    image: nats:nanoserver
    deploy:
      endpoint_mode: dnsrr
      placement:
        constraints:
        - node.platform.os == windows
    networks:
      - app-net

  signup-save-handler:
    image: dockersamples/mta-dev-signup-save-handler:v1
    deploy:
      endpoint_mode: dnsrr
      placement:
        constraints:
        - node.platform.os == windows
      replicas: 4
    networks:
      - app-net

networks:
  app-net:

secrets:
  signup-db.connectionstring:
    external:
      name: signup-db-v2.connectionstring
